server:
  port: 8011

spring:
  application:
    name: spring-cloud-netflix-web-feign

management:
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always
      
#开启熔断器
feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eurka/
