server:
  port: 8010

spring:
  application:
    name: spring-cloud-netflix-web-ribbon
  #配置项目本地配置优先于configserver配置
  cloud:
    config:
      allow-override: true
      override-none: true
management:
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
