server:
  port: 8003

spring:
  application:
    name: spring-cloud-netflix-web-feign
  #配置项目本地配置优先于configserver配置
  cloud:
    config:
      allow-override: true
      override-none: true
  zipkin:
    base-url: http://localhost:9411
management:
  endpoint:
    health:
      show-details: always
      

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eurka/
