server:
  port: 8001

spring:
  application:
    name: spring-cloud-netflix-service-admin
  cloud:
    config:
      allow-override: true
      override-none: true
  zipkin:
    base-url: http://localhost:9411

management:
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/